import type {
  CommunityPost,
  Deal,
  House,
  Product,
  Store,
} from "@/features/business/domain";

const houseImage = "/images/home/housing-history-2024.png";
const dealImage = "/images/home/group-buy-hotpot.png";
const productImage = "/images/home/fresh-produce.png";
const postImage = "/images/home/hangzhou-community.png";

export const demoStores = [
  {
    id: "10000000-0000-0000-0000-000000000001",
    name: "小满生鲜武林店",
    category: "supermarket",
    district: "拱墅区",
    address: "武林路演示地址 18 号",
    deliveryMinutes: 30,
    minimumOrder: 20,
    imageSrc: productImage,
    isDemo: true,
  },
  {
    id: "10000000-0000-0000-0000-000000000002",
    name: "蓝鲸生活超市",
    category: "supermarket",
    district: "西湖区",
    address: "曙光路演示地址 66 号",
    deliveryMinutes: 40,
    minimumOrder: 25,
    imageSrc: productImage,
    isDemo: true,
  },
  {
    id: "10000000-0000-0000-0000-000000000003",
    name: "山野火锅武林店",
    category: "restaurant",
    district: "拱墅区",
    address: "体育场路演示地址 88 号",
    deliveryMinutes: null,
    minimumOrder: 0,
    imageSrc: dealImage,
    isDemo: true,
  },
  {
    id: "10000000-0000-0000-0000-000000000004",
    name: "湖畔咖啡实验店",
    category: "cafe",
    district: "西湖区",
    address: "北山街演示地址 28 号",
    deliveryMinutes: null,
    minimumOrder: 0,
    imageSrc: dealImage,
    isDemo: true,
  },
] as const satisfies readonly Store[];

type HouseRow = readonly [
  suffix: string,
  name: string,
  district: string,
  address: string,
  priceMonthly: number,
  roomType: string,
  areaSqm: number,
  petsAllowed: boolean,
  available: boolean,
  subwayDistanceM: number,
  description: string,
  tags: readonly string[],
];

const houseRows: readonly HouseRow[] = [
  [
    "0001",
    "武林晴川一居室",
    "拱墅区",
    "武林广场演示房源 A",
    3280,
    "一居室",
    43,
    true,
    true,
    480,
    "采光良好，近地铁，允许养猫。",
    ["宠物友好", "近地铁", "朝南"],
  ],
  [
    "0002",
    "中山北路温馨一居",
    "拱墅区",
    "中山北路演示房源 B",
    3480,
    "一居室",
    46.5,
    true,
    true,
    620,
    "独立厨房，商业配套方便。",
    ["宠物友好", "独立厨房"],
  ],
  [
    "0003",
    "西湖文化广场小两居",
    "拱墅区",
    "文晖路演示房源 C",
    4200,
    "两居室",
    62,
    true,
    true,
    350,
    "两居室，适合两人合租。",
    ["近地铁", "两居室"],
  ],
  [
    "0004",
    "凤起路精装一居",
    "拱墅区",
    "凤起路演示房源 D",
    3850,
    "一居室",
    48,
    false,
    true,
    260,
    "精装修，不允许饲养宠物。",
    ["精装修", "近地铁"],
  ],
  [
    "0005",
    "保俶路阳光开间",
    "西湖区",
    "保俶路演示房源 E",
    2990,
    "开间",
    32,
    true,
    true,
    900,
    "小户型，适合一人居住。",
    ["低预算", "宠物友好"],
  ],
  [
    "0006",
    "黄龙安静一居室",
    "西湖区",
    "黄龙演示房源 F",
    3600,
    "一居室",
    45,
    true,
    true,
    780,
    "环境安静，允许养猫。",
    ["安静", "宠物友好"],
  ],
  [
    "0007",
    "朝晖舒适两居",
    "拱墅区",
    "朝晖演示房源 G",
    3980,
    "两居室",
    65,
    false,
    true,
    700,
    "空间宽敞，暂不允许宠物。",
    ["两居室", "空间大"],
  ],
  [
    "0008",
    "庆春路通勤一居",
    "上城区",
    "庆春路演示房源 H",
    3390,
    "一居室",
    41,
    true,
    true,
    520,
    "通勤方便，允许小型宠物。",
    ["通勤方便", "宠物友好"],
  ],
  [
    "0009",
    "湖滨商圈开间",
    "上城区",
    "湖滨演示房源 I",
    4100,
    "开间",
    38,
    false,
    true,
    320,
    "商圈内房源，租金较高。",
    ["核心商圈", "近地铁"],
  ],
  [
    "0010",
    "大关性价比一居",
    "拱墅区",
    "大关演示房源 J",
    2680,
    "一居室",
    42,
    true,
    true,
    1100,
    "预算友好，距市中心较远。",
    ["性价比", "宠物友好"],
  ],
  [
    "0011",
    "文三路合租次卧",
    "西湖区",
    "文三路演示房源 K",
    2200,
    "合租",
    18,
    false,
    true,
    650,
    "合租次卧，公共厨房。",
    ["合租", "低预算"],
  ],
  [
    "0012",
    "武林广场已租一居",
    "拱墅区",
    "武林广场演示房源 L",
    3100,
    "一居室",
    40,
    true,
    false,
    400,
    "已出租，用于验证可用状态过滤。",
    ["已出租"],
  ],
];

export const demoHouses: readonly House[] = houseRows.map(
  ([
    suffix,
    name,
    district,
    address,
    priceMonthly,
    roomType,
    areaSqm,
    petsAllowed,
    available,
    subwayDistanceM,
    description,
    tags,
  ]) => ({
    id: `20000000-0000-0000-0000-00000000${suffix}`,
    name,
    district,
    address,
    priceMonthly,
    roomType,
    areaSqm,
    petsAllowed,
    available,
    subwayDistanceM,
    description,
    imageSrc: houseImage,
    tags,
    historicalYear: 2024,
    isDemo: true,
  }),
);

type DealRow = readonly [
  suffix: string,
  storeId: string | null,
  title: string,
  merchantName: string,
  category: string,
  originalPrice: number,
  salePrice: number,
  refundable: boolean,
  refundPolicyLabel: string,
  validUntil: string,
  address: string,
  description: string,
  tags: readonly string[],
  salesCount: number,
];

const dealRows: readonly DealRow[] = [
  [
    "0001",
    demoStores[2].id,
    "山野火锅双人餐",
    "山野火锅武林店",
    "火锅",
    268,
    168,
    true,
    "未使用且有效期内可申请退款",
    "2027-12-31",
    "体育场路演示地址 88 号",
    "锅底、荤菜、素菜和饮品组合。",
    ["双人餐", "可退款"],
    1280,
  ],
  [
    "0002",
    null,
    "江南小馆双人套餐",
    "江南小馆",
    "江浙菜",
    238,
    158,
    true,
    "未使用且有效期内可申请退款",
    "2027-10-31",
    "凤起路演示地址 56 号",
    "适合两人用餐。",
    ["双人餐", "江浙菜"],
    845,
  ],
  [
    "0003",
    demoStores[3].id,
    "湖畔咖啡下午茶",
    "湖畔咖啡实验店",
    "咖啡",
    96,
    58,
    false,
    "特价套餐不支持退款",
    "2027-09-30",
    "北山街演示地址 28 号",
    "两杯饮品和一份甜点。",
    ["下午茶", "不可退"],
    510,
  ],
  [
    "0004",
    null,
    "炭火烤肉两人餐",
    "炭火研究所",
    "烤肉",
    298,
    198,
    true,
    "未核销可申请退款",
    "2027-11-30",
    "武林路演示地址 21 号",
    "牛肉和蔬菜组合。",
    ["烤肉", "可退款"],
    960,
  ],
  [
    "0005",
    null,
    "亲子乐园家庭票",
    "星球亲子乐园",
    "亲子",
    180,
    109,
    true,
    "未预约未使用可退款",
    "2027-08-31",
    "西湖文化广场演示地址 5 号",
    "两大一小家庭票。",
    ["亲子", "周末"],
    430,
  ],
  [
    "0006",
    null,
    "轻食工作日午餐",
    "绿叶轻食",
    "轻食",
    68,
    39.9,
    false,
    "购买后不支持退款",
    "2027-06-30",
    "延安路演示地址 39 号",
    "工作日午餐时段使用。",
    ["工作日", "不可退"],
    620,
  ],
  [
    "0007",
    null,
    "日式料理双人套餐",
    "海月料理",
    "日料",
    358,
    228,
    true,
    "未使用且有效期内可退款",
    "2027-12-31",
    "庆春路演示地址 70 号",
    "刺身、寿司和热菜组合。",
    ["日料", "双人餐"],
    770,
  ],
  [
    "0008",
    null,
    "影院双人通兑券",
    "城市影城",
    "休闲娱乐",
    160,
    99,
    true,
    "未兑换可退款，特殊场次除外",
    "2027-12-31",
    "湖滨演示地址 12 号",
    "演示通兑券。",
    ["电影", "可退款"],
    2010,
  ],
];

export const demoDeals: readonly Deal[] = dealRows.map(
  ([
    suffix,
    storeId,
    title,
    merchantName,
    category,
    originalPrice,
    salePrice,
    refundable,
    refundPolicyLabel,
    validUntil,
    address,
    description,
    tags,
    salesCount,
  ]) => ({
    id: `30000000-0000-0000-0000-00000000${suffix}`,
    storeId,
    title,
    merchantName,
    category,
    originalPrice,
    salePrice,
    refundable,
    refundPolicyLabel,
    validUntil,
    address,
    description,
    imageSrc: dealImage,
    tags,
    salesCount,
    isDemo: true,
  }),
);

const productRows = [
  [
    "0001",
    0,
    "鲜牛奶 950ml",
    "乳品",
    15.9,
    "冷藏鲜牛奶。",
    ["早餐", "冷藏"],
    32,
    2,
  ],
  ["0002", 0, "无菌鸡蛋 10 枚", "蛋品", 18.8, "家庭装鸡蛋。", ["早餐"], 20, 1],
  ["0003", 0, "云南蓝莓 125g", "水果", 19.9, "盒装蓝莓。", ["水果"], 16, 0],
  [
    "0004",
    0,
    "番茄 500g",
    "蔬菜",
    8.9,
    "适合家常烹饪。",
    ["蔬菜", "家常菜"],
    40,
    3,
  ],
  [
    "0005",
    0,
    "鲜切牛肉 300g",
    "肉类",
    39.9,
    "火锅或快炒。",
    ["火锅", "肉类"],
    8,
    1,
  ],
  ["0006", 0, "手工面 400g", "主食", 7.9, "冷藏面条。", ["主食"], 25, 0],
  ["0007", 0, "生菜 300g", "蔬菜", 6.5, "沙拉和火锅均可。", ["蔬菜"], 21, 0],
  ["0008", 0, "原味酸奶 6 杯", "乳品", 24.9, "家庭分享装。", ["冷藏"], 14, 0],
  ["0009", 1, "矿泉水 12 瓶", "饮料", 21.9, "整箱饮用水。", ["整箱"], 12, 0],
  ["0010", 1, "香蕉 1kg", "水果", 12.8, "日常水果。", ["水果"], 28, 2],
  [
    "0011",
    1,
    "速冻水饺 500g",
    "速冻",
    22.9,
    "猪肉白菜口味。",
    ["速冻", "方便"],
    11,
    0,
  ],
  ["0012", 1, "洗衣液 2kg", "日用", 29.9, "家庭装。", ["日用"], 9, 0],
  ["0013", 1, "纸巾 12 包", "日用", 26.8, "抽纸组合装。", ["日用"], 0, 0],
  [
    "0014",
    1,
    "鸡胸肉 400g",
    "肉类",
    23.9,
    "轻食食材。",
    ["轻食", "肉类"],
    18,
    1,
  ],
  [
    "0015",
    1,
    "西兰花 400g",
    "蔬菜",
    9.9,
    "轻食和家常菜。",
    ["蔬菜", "轻食"],
    22,
    0,
  ],
  ["0016", 1, "即食燕麦 500g", "早餐", 16.9, "冲泡早餐。", ["早餐"], 15, 0],
] as const;

export const demoProducts = productRows.map(
  ([
    suffix,
    storeIndex,
    name,
    category,
    price,
    description,
    tags,
    stock,
    reserved,
  ]) => ({
    id: `40000000-0000-0000-0000-00000000${suffix}`,
    storeId: demoStores[storeIndex].id,
    name,
    category,
    price,
    description,
    imageSrc: productImage,
    tags,
    stock,
    reserved,
    availableStock: stock - reserved,
    isDemo: true,
  }),
) satisfies Product[];

type CommunityPostRow = readonly [
  suffix: string,
  category: string,
  title: string,
  excerpt: string,
  content: string,
  authorName: string,
  locationLabel: string,
  tags: readonly string[],
  likeCount: number,
  commentCount: number,
];

const communityPostRows: readonly CommunityPostRow[] = [
  [
    "0001",
    "周末去哪儿",
    "西湖边适合慢慢走的一条路线",
    "从北山街出发，避开最拥挤的路段。",
    "这是一篇演示社区内容，不代表实时路况。",
    "阿梨的杭州周末",
    "北山街",
    ["散步", "西湖"],
    328,
    42,
  ],
  [
    "0002",
    "租房避坑",
    "带猫租房前我会确认的 6 件事",
    "合同、家具损坏和公共区域规则都要看。",
    "这是一篇演示经验帖，正式规则以知识库和合同为准。",
    "橘猫租客",
    "武林广场",
    ["租房", "养猫"],
    512,
    68,
  ],
  [
    "0003",
    "附近美食",
    "一个人也适合去的三家小店",
    "座位不拥挤，出餐比较快。",
    "店铺仅为演示内容，附近真实 POI 请使用高德工具。",
    "小周吃杭州",
    "凤起路",
    ["一人食"],
    206,
    25,
  ],
  [
    "0004",
    "超市好物",
    "一百元做三顿晚饭的采购清单",
    "牛肉、番茄、鸡蛋和蔬菜的组合。",
    "可点击问小智，让它根据库存生成购物清单。",
    "认真买菜的林林",
    "武林路",
    ["买菜", "清单"],
    188,
    19,
  ],
  [
    "0005",
    "亲子活动",
    "雨天也能玩的室内亲子路线",
    "上午乐园，下午绘本馆。",
    "这是一篇演示路线。",
    "小树妈妈",
    "西湖文化广场",
    ["亲子", "雨天"],
    421,
    50,
  ],
  [
    "0006",
    "咖啡探店",
    "北山街安静办公咖啡馆体验",
    "工作日上午人少，插座充足。",
    "这是一篇演示探店内容。",
    "陈同学",
    "北山街",
    ["咖啡", "办公"],
    276,
    31,
  ],
  [
    "0007",
    "团购经验",
    "买团购前先看这三个退款字段",
    "有效期、未使用退款和预约限制。",
    "正式退款规则请查询知识库。",
    "省钱观察员",
    "杭州",
    ["团购", "退款"],
    362,
    44,
  ],
  [
    "0008",
    "通勤生活",
    "住在武林广场附近的一周感受",
    "通勤方便，但需要权衡租金与空间。",
    "房源价格为演示数据。",
    "北漂回杭",
    "武林广场",
    ["通勤", "租房"],
    195,
    22,
  ],
  [
    "0009",
    "家常菜",
    "番茄牛肉面的一人份做法",
    "购物清单可以直接交给小智查询库存。",
    "食谱为演示内容。",
    "阿江厨房",
    "杭州",
    ["食谱", "一人食"],
    144,
    13,
  ],
  [
    "0010",
    "城市生活",
    "周末不赶时间的生活提案",
    "从早餐、散步到晚餐的一天。",
    "内容用于演示社区卡片。",
    "慢慢生活社",
    "杭州",
    ["周末", "生活方式"],
    304,
    37,
  ],
];

export const demoCommunityPosts: readonly CommunityPost[] =
  communityPostRows.map(
    ([
      suffix,
      category,
      title,
      excerpt,
      content,
      authorName,
      locationLabel,
      tags,
      likeCount,
      commentCount,
    ]) => ({
      id: `50000000-0000-0000-0000-00000000${suffix}`,
      category,
      title,
      excerpt,
      content,
      authorName,
      locationLabel,
      coverImageSrc: postImage,
      tags,
      likeCount,
      commentCount,
      isDemo: true,
    }),
  );
