import type { HomeHighlight } from "@/features/home/home-types";

export const homeHighlights = [
  {
    id: "housing-wulin-2024",
    kind: "housing",
    source: "housing_history_2024",
    historicalYear: 2024,
    title: "武林广场旁一居室",
    eyebrow: "2024 历史房源示例",
    location: "拱墅区 · 武林商圈",
    priceText: "¥3280/月",
    detail: "约 38㎡ · 一居室 · 历史价格记录",
    imageSrc: "/images/home/housing-history-2024.png",
    imageAlt: "采光明亮的紧凑型出租屋室内",
    isDemo: true,
  },
  {
    id: "deal-hotpot-for-two",
    kind: "deal",
    source: "supabase_mock",
    title: "双人鲜切牛肉火锅",
    eyebrow: "周末聚餐灵感",
    location: "拱墅区 · 湖墅南路",
    priceText: "¥128",
    detail: "双人套餐 · 菜品与价格均为演示",
    imageSrc: "/images/home/group-buy-hotpot.png",
    imageAlt: "摆放整齐的双人中式火锅",
    isDemo: true,
  },
  {
    id: "product-seasonal-fruit",
    kind: "product",
    source: "supabase_mock",
    title: "当季鲜果组合",
    eyebrow: "今日采购灵感",
    location: "杭州 · 线上超市演示",
    priceText: "¥16.9",
    detail: "葡萄、桃与樱桃 · 商品与价格均为演示",
    imageSrc: "/images/home/fresh-produce.png",
    imageAlt: "自然光下的新鲜葡萄、桃和樱桃",
    isDemo: true,
  },
  {
    id: "community-west-lake-spring",
    kind: "community",
    source: "supabase_mock",
    title: "西湖边的春日散步路线",
    eyebrow: "社区灵感",
    location: "西湖区 · 北山街",
    author: "小杭（演示用户）",
    detail: "约 3.2km · 轻松步行路线",
    imageSrc: "/images/home/hangzhou-community.png",
    imageAlt: "春日杭州西湖湖畔步道",
    isDemo: true,
  },
] as const satisfies readonly HomeHighlight[];
